# Generated by Django 5.2.7 on 2025-10-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='busSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('deck', models.CharField(choices=[('lower', 'Lower'), ('upper', 'Upper'), ('end_center', 'End Center')], max_length=20)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=20)),
                ('type', models.CharField(choices=[('sleeper_sit', 'Sleeper Sit'), ('seater', 'Seater')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('busId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_seat', to='busModel.busmodel')),
            ],
        ),
    ]
