# Generated by Django 5.2.7 on 2025-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busSeats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busseat',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
