# Generated by Django 5.2.7 on 2025-10-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busOwnerModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='busModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('start_location', models.CharField(blank=True, max_length=100, null=True)),
                ('end_location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_number', models.CharField(max_length=100)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('bus_features', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='busOwnerModel.busowner')),
            ],
        ),
    ]
