# Generated by Django 5.2.7 on 2025-10-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busModel', '0001_initial'),
        ('cityModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='cityModel.citymodel'),
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='cityModel.citymodel'),
        ),
    ]
