# Generated by Django 5.2.7 on 2025-10-11 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('busModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_deck_left_sleeper_sit', models.BooleanField(default=False)),
                ('lower_deck_left_sleeper_sit_row', models.IntegerField(default=0)),
                ('lower_deck_left_sleeper_sit_count', models.IntegerField(default=0)),
                ('lower_deck_left_seater', models.BooleanField(default=False)),
                ('lower_deck_left_seater_row', models.IntegerField(default=0)),
                ('lower_deck_left_seater_count', models.IntegerField(default=0)),
                ('lower_deck_right_sleeper_sit', models.BooleanField(default=False)),
                ('lower_deck_right_sleeper_sit_row', models.IntegerField(default=0)),
                ('lower_deck_right_sleeper_sit_count', models.IntegerField(default=0)),
                ('lower_deck_right_seater', models.BooleanField(default=False)),
                ('lower_deck_right_seater_row', models.IntegerField(default=0)),
                ('lower_deck_right_seater_count', models.IntegerField(default=0)),
                ('upper_deck_left_sleeper_sit', models.BooleanField(default=False)),
                ('upper_deck_left_sleeper_sit_row', models.IntegerField(default=0)),
                ('upper_deck_left_sleeper_sit_count', models.IntegerField(default=0)),
                ('upper_deck_left_seater', models.BooleanField(default=False)),
                ('upper_deck_left_seater_row', models.IntegerField(default=0)),
                ('upper_deck_left_seater_count', models.IntegerField(default=0)),
                ('upper_deck_right_sleeper_sit', models.BooleanField(default=False)),
                ('upper_deck_right_sleeper_sit_row', models.IntegerField(default=0)),
                ('upper_deck_right_sleeper_sit_count', models.IntegerField(default=0)),
                ('upper_deck_right_seater', models.BooleanField(default=False)),
                ('upper_deck_right_seater_row', models.IntegerField(default=0)),
                ('upper_deck_right_seater_count', models.IntegerField(default=0)),
                ('end_center_seater', models.BooleanField(default=False)),
                ('busId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='busModel.busmodel')),
            ],
        ),
    ]
