# Generated by Django 5.2.7 on 2025-10-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citymodel',
            old_name='end_location',
            new_name='cityName',
        ),
        migrations.RemoveField(
            model_name='citymodel',
            name='start_location',
        ),
    ]
